### ISSUE TITLE
Typo in comparision

### ISSUE THREAD

**Issue by KasparEtter** [jstrnbrg/hardware-wallets#1]
https://github.com/jstrnbrg/hardware-wallets/blob/ba427de3f23f97a8272418c0a72e477f86831ffc/index.html#L2061
https://github.com/jstrnbrg/hardware-wallets/blob/ba427de3f23f97a8272418c0a72e477f86831ffc/index.html#L2069

**Comment by jstrnbrg** [comment]
Thanks, fixed :)
